### ISSUE TITLE
"Model not yet available" for every model

### ISSUE THREAD

**Issue by AmazingMilesMorales** [sketchfab/unity-plugin#15] opened 2022-03-29 18:29 UTC
I am using Unity 2020.3.28f1 and version 1.2.1 of the plugin, and while I am able to browse Sketchfab through the plugin, no matter even if I was previously able to download a model through the plugin, the following error displays:

![image](https://user-images.githubusercontent.com/43057080/160680491-fe01b373-e534-4fdc-8149-78c57b4b663a.png)

**Comment by AurL** [comment] 2022-03-30 07:01
Hi, 
It seems that a recent change in our API made all the models unavailable for the Unity plugin. 
It seems to affects all the models, it's being investigated

I keep you posted, thanks for reporting

**Edit:** a quick fix will be pushed ASAP. In the meantime, you can fix by editing `Assets/Sketchfab For Unity/Scripts/AssetBrowser/SketchfabBrowserManager.cs` at line 124 to
`isModelAvailable = true`

**Comment by AurL** [comment] 2022-03-30 08:27
~@LeoLlopiz Do you have an estimate of the last time you have been able to download a model through the plugin ?~
We identified the cause and a fix will go live soon 👍
As the change is on Sketchfab API side, there will be nothing to do or update on your side

**Comment by AurL** [comment] 2022-04-01 08:01
The fix has been released on Sketchfab size so the plugin should now work as expected👍

**Closed as completed** 2022-04-01 08:01 UTC
Labels: bug
